name: 'Build corne nice_nano_v2 nice_view revert'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      nav: '["invertedt"]'
      layers: '["flip"]'
      clipboard: '["mac"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_RGB_UNDERGLOW=n\nCONFIG_WS2812_STRIP=n\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
  
